sudo: required

services:
  - docker

language: python

script:
  - python -m pytest -v

after_success:
  - echo $TRAVIS_REPO_SLUG
  - docker build -f Dockerfile -t $TRAVIS_REPO_SLUG:latest .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin; docker push $TRAVIS_REPO_SLUG:latest; fi
