sudo: required

global:
  - LOWERCASE_REPO_SLUG="${TRAVIS_REPO_SLUG,,}"
services:
  - docker

language: python

script:
  - python -m pytest -v

after_success:
  - echo $LOWERCASE_REPO_SLUG
  - docker build -f Dockerfile -t $LOWERCASE_REPO_SLUG:latest .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin; docker push $LOWERCASE_REPO_SLUG:latest; fi
